#!/usr/bin/env python3

#Python 3.7.8+
import re
import sys

MSG_WARN = 'WARN:'
MSG_FAIL = 'FAIL:'

EXCODE_FAIL = 1
EXCODE_OK   = 0

DEFS_HEAD = r"""
// <afont57>
#if __cplusplus >= 201703L
#define AFONT57_INLINE inline
#else
#define AFONT57_INLINE
#endif

#if defined(PROGMEM)
// Adarfuit GFX library uses PROGMEM to store font data (and use pgm_* functions to read it), so PROGMEM is required
#define AFONT57_PROGMEM PROGMEM
#else
#define AFONT57_PROGMEM
#endif
// </afont57>

// <afont57>
// Drop-in replacement gfxfont that works like default fixed font
// Obeys same convention with top-left corner char coord

// Make byte by 8 bits
#define fontByteMake(bit7, bit6, bit5, bit4, bit3, bit2, bit1, bit0) (uint8_t) \
        ( \
         (uint8_t)(((uint8_t)(bit7 & 0x1)) << 7) | \
         (uint8_t)(((uint8_t)(bit6 & 0x1)) << 6) | \
         (uint8_t)(((uint8_t)(bit5 & 0x1)) << 5) | \
         (uint8_t)(((uint8_t)(bit4 & 0x1)) << 4) | \
         (uint8_t)(((uint8_t)(bit3 & 0x1)) << 3) | \
         (uint8_t)(((uint8_t)(bit2 & 0x1)) << 2) | \
         (uint8_t)(((uint8_t)(bit1 & 0x1)) << 1) | \
         (uint8_t)(bit0 & 0x1) \
         )

// get byte bit
#define fontByteGetBit(byteValue, bitindex) ((uint8_t)((((uint8_t)(byteValue)) >> (bitindex)) & 0x01))

// Transpose bits for FontChar
// Default fixed font:
// Declared 5x7
// Actual font cell is 5x8, software uses 6x8 print cells (that is, adds 1px margin to right of each char)
// So, vertical pseudograph is linked, horizontal is not (that is, chars are separated by 1px enforced gap)
// Font char stored 5 bytes, matrix 8x5, rotated 90 deg CW
// gfxFont 
// Char stored as pixel stream left-to-right-top-to-bottom as in byte0bit0, byte0bit1, byte7bit1, ... byte1bit0, ...
// This macro transposes 8x5 bytes to GfxFont format
#define BG fontByteGetBit // Synonym
#define BM fontByteMake // Synonym
#define FC(b0, b1, b2, b3, b4) \
        BM( \
            BG(b0,0), BG(b1,0), BG(b2,0), BG(b3,0), BG(b4,0), \
            BG(b0,1), BG(b1,1), BG(b2,1) \
          ), \
        BM(                               BG(b3,1), BG(b4,1), \
            BG(b0,2), BG(b1,2), BG(b2,2), BG(b3,2), BG(b4,2), \
            BG(b0,3) \
          ), \
        BM( \
            BG(b1,3), BG(b2,3), BG(b3,3), BG(b4,3), \
            BG(b0,4), BG(b1,4), BG(b2,4), BG(b3,4) \
          ), \
        BM( \
                                                    BG(b4,4), \
            BG(b0,5), BG(b1,5), BG(b2,5), BG(b3,5), BG(b4,5), \
            BG(b0,6), BG(b1,6) \
          ), \
        BM( \
                                BG(b2,6), BG(b3,6), BG(b4,6), \
            BG(b0,7), BG(b1,7), BG(b2,7), BG(b3,7), BG(b4,7) \
          )
// </afont57>
""".lstrip()

DEFS_TAIL = r"""
// <afont57>
#undef  FC
#undef  BM
#undef  BG
#undef  fontByteGetBit
#undef  fontByteMake
// </afont57>

// <afont57>
#undef AFONT57_INLINE
#undef AFONT57_PROGMEM
// </afont57>
"""

FILE_HEAD = """
#pragma once
""".lstrip()

FILE_HEAD_DATA_SIZE = 0

FONT_BITMAP_HEAD = """
// <afont57Bitmaps>
AFONT57_INLINE const uint8_t {fontname}Bitmaps[] {PROGMEM}= {{
""".strip()

FONT_BITMAP_TAIL = """
}};
// </afont57Bitmaps>
""".lstrip()

FONT_GLYPH_HEAD = """
AFONT57_INLINE const GFXglyph {fontname}Glyphs[] {PROGMEM}= {{
""".rstrip()

#typedef struct {
#  uint16_t bitmapOffset; ///< Pointer into GFXfont->bitmap
#  uint8_t width;         ///< Bitmap dimensions in pixels
#  uint8_t height;        ///< Bitmap dimensions in pixels
#  uint8_t xAdvance;      ///< Distance to advance cursor (x axis)
#  int8_t xOffset;        ///< X dist from cursor pos to UL corner
#  int8_t yOffset;        ///< Y dist from cursor pos to UL corner
#} GFXglyph;

FONT_GLYPH_ITEM = "{{ {bitmapOffset}, {width}, {height}, {xAdvance}, {xOffset}, {yOffset} }}"

FONT_GLYPH_DATA_SIZE = 2+1+1+1+1+1

FONT_GLYPH_TAIL = """
}};
""".lstrip()

#/// Data stored for FONT AS A WHOLE
#typedef struct {
#  uint8_t *bitmap;  ///< Glyph bitmaps, concatenated
#  GFXglyph *glyph;  ///< Glyph array
#  uint16_t first;   ///< ASCII extents (first char)
#  uint16_t last;    ///< ASCII extents (last char)
#  uint8_t yAdvance; ///< Newline distance (y axis)
#} GFXfont;

FONT_BODY_DEFS = """
AFONT57_INLINE const GFXfont {fontname} {PROGMEM}= {{
  (uint8_t  *){fontname}Bitmaps,
  (GFXglyph *){fontname}Glyphs,
  {fontcharfrom}, {fontcharto}, {fontheight}
}};
""".lstrip()

FILE_TAIL = """
// fontdatasize approx: {fontdatasize} bytes
// Generated by afont572gfxfont from 5x7 font definition file
"""

FILE_TAIL_DATA_SIZE = 4+4+2+2+1

def processArgs(args):
  head = re.compile(r".*\[\s*\].*{\s*", flags=re.IGNORECASE)

  # We do not support all the cases in regexp
  # some errors catched in int values parsing (special case is absense of last comma)
  # so we have adequete balance here
  pattern = re.compile(r"(0x[0-9a-f]+|0b[0-9a-f]+|0|[1-9][0-9]*)[ \t]*(,|\)[ \t]*,|)[ \t]*(//.*$|)", flags=re.IGNORECASE)

  tail = re.compile(r"\s*}\s*;", flags=re.IGNORECASE)

  with open(args.fontin, "rt", encoding="utf-8") as f:
    linesin = [linein.rstrip("\n\r") for linein in f]

  FONT_IN_BYTES_PER_CHAR = 5 # actual char matrix 5 bytes

  byteIndex = 0
  charIndex = 0
  linesout = []

  head_found = False
  tail_found = False

  fontdata = []
  fontcomm = {}

  charComment = ""

  lineNumber = 0

  for linein in linesin:
    lineNumber += 1
    if not head_found:
      if head.match(linein):
        head_found = True
        #print("Font head found")
      else:
        pass
      continue
    elif not tail_found:
      if tail.match(linein):
        tail_found = True
        #print("Font tail found")
        continue
    elif tail_found:
      continue

    # Here is the body of the font, we need to process it

    if (linein.strip() ==""):
      # skip pure empty lines
      #linesout.append(linein)
      continue

    if (linein.strip().startswith("//")):
      # skip pure comment lines
      #linesout.append(linein)
      continue

    matches = list(pattern.finditer(linein))
    if (len(matches) == 0):
      continue

    matchIndex = 0
    for m in matches:
      try:
        value = int(m.group(1), 0)
      except Exception as e:
        value = None
      
      if (value is None) or (value < 0) or (value > 255):
        print(MSG_WARN+f"Invalid value in line {lineNumber}: '{m.group(1)}' -- ignored")
        continue # skip invalid lines

      sep     = m.group(2)
      comment = m.group(3)

      if (comment != ""):
        if (charComment != ""):
          charComment += " "
        charComment += comment

      fontdata.append(value)
      byteIndex += 1
      matchIndex += 1

      if ((byteIndex % FONT_IN_BYTES_PER_CHAR) == 0):
        if (charComment != ""):
          fontcomm[charIndex] = charComment
          charComment = ""
        charIndex += 1

  #font is loaded

  if not head_found:
      print(MSG_FAIL + "Font array head not found")
      return EXCODE_FAIL

  if not tail_found:
      print(MSG_FAIL + "Font array tail not found")
      return EXCODE_FAIL

  FONT_HEIGHT = 8

  fontdefs = { }

  fontname = args.fontname
  if (fontname != None) and (fontname != ""):
    pass # keep
  else:
    from pathlib import Path
    fontname = Path(args.fontout).stem

  fontdefs["fontname"] = fontname
  fontdefs["fontheight"] = FONT_HEIGHT

  if (args.noprogmem):
    fontdefs["PROGMEM"] = ""
  else:
    fontdefs["PROGMEM"] = "AFONT57_PROGMEM" + " "

  # source font chars expected to be from char code 0 (up to 255)

  # may be params someday
  charFrom  = 0   # from char do export
  charTo    = 255 # from char do export
  charCount = (charTo-charFrom)+1 # number of chars to export

  goodCount = (charTo+1) * FONT_IN_BYTES_PER_CHAR

  if (len(fontdata) > goodCount):
    print(MSG_WARN + f"Font size {len(fontdata)} bytes does not match expected size of {goodCount} bytes")
  elif (len(fontdata) < goodCount):
    print(MSG_FAIL + f"FAIL: font size {len(fontdata)} bytes is less than expected size of {goodCount} bytes")
    return EXCODE_FAIL

  fontdatasize = FILE_HEAD_DATA_SIZE + charCount * FONT_IN_BYTES_PER_CHAR + FONT_GLYPH_DATA_SIZE*charCount + FILE_TAIL_DATA_SIZE

  fontdefs["fontdatasize"] = fontdatasize
  fontdefs["fontcharfrom"] = charFrom
  fontdefs["fontcharto"]   = charTo

  linesout = []

  linesout.append(FILE_HEAD.format(**fontdefs))
  linesout.append(DEFS_HEAD)
  linesout.append(FONT_BITMAP_HEAD.format(**fontdefs))

  # font

  INDENT = "    "
  FIRST  = " FC("

  byteCount = 0
  for charIndex in range(charFrom, charTo+1):
    if (args.nocomcode):
      pass
    else:
      lineout = ""
      lineout += "\n"
      lineout += INDENT + "// 0x{:02x} {:3d}".format(charIndex, charIndex)
      if (charIndex >= 0x20) and (charIndex < 127):
        lineout += " '{}'".format(chr(charIndex))
      linesout.append(lineout)

    for byteIndex in range(charIndex * FONT_IN_BYTES_PER_CHAR, (charIndex+1) * FONT_IN_BYTES_PER_CHAR):
      lineout = ""
      if (byteIndex == (charIndex * FONT_IN_BYTES_PER_CHAR)):
        lineout += FIRST
      else:
        lineout += INDENT
      lineout += "0b{:08b}".format(fontdata[byteIndex])
      if (byteIndex+1 < (charIndex+1) * FONT_IN_BYTES_PER_CHAR):
        lineout += ","
      else:
        lineout += "),"
        if (fontcomm.get(charIndex) != None):
          lineout += " " + fontcomm.get(charIndex)
      linesout.append(lineout)
      byteCount += 1

  linesout.append(FONT_BITMAP_TAIL.format(**fontdefs))
  linesout.append(FONT_GLYPH_HEAD.format(**fontdefs))

  for charIndex in range(charFrom, charTo+1):
    charGlyph = {}
    charGlyph["bitmapOffset"] = (charIndex - charFrom) * FONT_IN_BYTES_PER_CHAR
    charGlyph["width"] = 5
    charGlyph["height"] = 8 # actually, 8 pixels (as 98 bits), but the last one is used for spacing in alpha, unless pseudograph
    charGlyph["xAdvance"] = 6 # 5 pixels + 1 pixel spacing enforced on all chars
    # simulate default fixed font, with hot pixel at top left corner
    charGlyph["xOffset"] = 0
    charGlyph["yOffset"] = 0
    lineout = INDENT + FONT_GLYPH_ITEM.format(**charGlyph)
    lineout += ","
    linesout.append(lineout)

  linesout.append(FONT_GLYPH_TAIL.format(**fontdefs))
  linesout.append(FONT_BODY_DEFS.format(**fontdefs))
  linesout.append(DEFS_TAIL)
  linesout.append(FILE_TAIL.format(**fontdefs))

  with open(args.fontout, "wt", encoding="utf-8") as f:
    for lineout in linesout:
      f.write(lineout+'\n')

  print(f"Converted {byteCount} bytes")

  return(EXCODE_OK)

def main(argv):

  import argparse

  parser = argparse.ArgumentParser(description='Adafruit Gfx FONT 5x7 definition converter to GFXFont')
  parser.add_argument('fontin', type=str, help='Input 5x7 font file (.h or .cpp)')
  parser.add_argument('fontout', type=str, help='Output 5x7 gfxfont file (.h or .cpp)')
  parser.add_argument('--fontname', type=str, help='Name for the generated GFXFont, default is name of output file without extension', default=None)
  parser.add_argument('--nocomcode', help='Do not add char code comments', action='store_true')
  parser.add_argument('--noprogmem', help='Do not add store font data in program memory (PROGMEM) definition', action='store_true')
  parser.add_argument('--debug', help='Print extra info on exceptions', action='store_true')
  args = parser.parse_args(argv)

  try:
    if processArgs(args) != 0: 
      return(EXCODE_FAIL)
    print("OK!")
  except Exception as e:
    if hasattr(e,'reason'): print("FAIL "+e.reason); 
    else: print("FAIL:"+str(e))
    if (args.debug): raise e
    print(MSG_FAIL+"Error while in operation")
    return(EXCODE_FAIL)
  
  return(EXCODE_OK)

if __name__ == "__main__":
  sys.exit(main(sys.argv[1:]))
